const config = {
  github: {
    username: 'bryant2305',
    sortBy: 'stars',
    limit: 6,
    exclude: {
      forks: true,
      projects: ['bryant2305.github.io', 'bryant2305'],
    },
  },
  social: {
    linkedin: 'bryant-perez-garcia-6b5913252',
    twitter: '',
    mastodon: '',
    facebook: '',
    instagram: '',
    youtube: '',
    dribbble: '',
    behance: '',
    medium: '',
    dev: '',
    stackoverflow: '',
    skype: '',
    telegram: '',
    website: 'https://bryant2305.github.io/',
    phone: '+18294322305',
    email: 'bryantperezgarcia005@gmail.com',
  },
  resume: {
    fileUrl: '',
  },
  skills: [
    'AWS',
    'AWS Lambda',
    'Amazon S3',
    'DynamoDB',
    'Amazon SQS',
    'Amazon SNS',
    'API Gateway',
    'IAM',
    'Amazon Rekognition',
    'CloudFormation',
    'AWS CDK',
    'Terraform',
    'Kubernetes',
    'Docker',
    'CI/CD',
    'GitHub Actions',
    'Serverless',
    'TypeScript',
    'Node.js',
    'NestJS',
    'Python',
    'FastAPI',
    'PHP',
    'Laravel',
    '.NET',
    'MicroServices',
    'gRPC',
    'RESTful APIs',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'OpenAI API',
    'Git',
  ],
  experiences: [
    {
      company: 'Oficina Gubernamental de Tecnologías de la Información y Comunicación (OGTIC)',
      position: 'Backend Developer Intern',
      from: 'April 2023',
      to: 'June 2023',
      companyLink: 'https://ogtic.gob.do',
    },
    {
      company: 'Oficina Gubernamental de Tecnologías de la Información y Comunicación (OGTIC)',
      position: 'Cloud & Backend Developer',
      from: 'June 2023',
      to: 'September 2025',
      companyLink: 'https://ogtic.gob.do',
    },
    {
      company: 'Office Libations',
      position: 'Software & Cloud Engineer',
      from: 'September 2025',
      to: 'Present',
      companyLink: 'https://www.officelibations.com',
    },
  ],
  certifications: [
    {
      name: 'AWS Certified Solutions Architect - Associate',
      body: 'Amazon Web Services (AWS)',
      year: '2025',
      link: '',
    },
    {
      name: 'AWS Knowledge: Cloud Essentials',
      body: 'Amazon Web Services (AWS)',
      year: '2024',
      link: 'https://www.credly.com/badges/946b3d5f-5fa6-4dd5-a159-b872db9c63bc/linked_in_profile',
    },
    {
      name: 'AWS Knowledge: Serverless',
      body: 'Amazon Web Services (AWS)',
      year: '2025',
      link: 'https://www.credly.com/badges/bf6c973b-6837-47e9-b280-a8283557b003',
    },
  ],
  externalProjects: [],
  blog: {},
  googleAnalytics: {
    id: '',
  },
  hotjar: {
    id: '',
    snippetVersion: 6,
  },
  seo: {
    title: 'Bryant Perez Garcia - Portfolio',
    description:
      'AWS Certified Solutions Architect & Cloud Engineer specializing in serverless architectures, microservices, Infrastructure as Code, and AI-powered automation on AWS.',
    imageURL: 'https://bryant2305.github.io/assets/preview.png',
  },
  themeConfig: {
    defaultTheme: 'dark',
    disableSwitch: false,
    respectPrefersColorScheme: true,
    hideAvatarRing: false,
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'procyon',
    ],
    customTheme: {
      primary: '#fc055b',
      secondary: '#219aaf',
      accent: '#e8d03a',
      neutral: '#2A2730',
      'base-100': '#E3E3ED',
      '--rounded-box': '3rem',
      '--rounded-btn': '3rem',
    },
  },
};

export default config;
