const config = {
  github: {
    username: 'bryant2305',
    sortBy: 'updated', // Opciones: 'stars' | 'updated'
    limit: 8,
    exclude: {
      forks: true,
      projects: ['bryant2305.github.io', 'bryant2305'],
    },
  },
  social: {
    linkedin: 'www.linkedin.com/in/bryant-perez-garcia-6b5913252',
    twitter: '',
    mastodon: '',
    facebook: '',
    instagram: '',
    youtube: '',
    dribbble: '',
    behance: '',
    medium: '',
    dev: '',
    stackoverflow: '',
    skype: '',
    telegram: '',
    website: 'https://bryant2305.github.io',
    phone: '',
    email: 'bryantperezgarcia005@gmail.com',
  },
  resume: {
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  skills: [
    'PHP',
    'Laravel',
    'JavaScript',
    'Node.js',
    'Nest.js',
    'Serverless',
    'MicroServices',
    'Caching',
    'Redis',
    'MySQL',
    'SQL',
    'MongoDB',
    'Git',
    'Docker',
    'PHPUnit',
    'AWS',
  ],
  experiences: [
    {
      company: 'OGTIC',
      position: 'Back-end Developer Intern',
      from: 'April 2023',
      to: 'Jun 2023',
      companyLink: 'https://ogtic.gob.do/',
    },
    {
      company: 'OGTIC',
      position: 'Back-end Developer',
      from: 'Jun 2023',
      to: 'Present',
      companyLink: 'https://ogtic.gob.do/',
    },
  ],
  certifications: [
    {
      name: 'Sample Certification',
      body: 'Description of certification',
      year: 'March 2022',
      link: 'https://example.com',
    },
  ],
  // Puedes agregar proyectos externos aquí si deseas
  externalProjects: [],
  blog: {
    // source: 'dev', // medium | dev
    // username: '', // Dejar vacío para ocultar la sección del blog
    // limit: 2,
  },
  googleAnalytics: {
    id: '',
  },
  hotjar: {
    id: '',
    snippetVersion: 6,
  },
  themeConfig: {
    defaultTheme: 'dark',
    disableSwitch: false,
    respectPrefersColorScheme: true,
    hideAvatarRing: false,
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'procyon',
    ],
    customTheme: {
      primary: '#fc055b',
      secondary: '#219aaf',
      accent: '#e8d03a',
      neutral: '#2A2730',
      'base-100': '#E3E3ED',
      '--rounded-box': '3rem',
      '--rounded-btn': '3rem',
    },
  },
};

export default config;
